name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '22 2 * * 3'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push genshin-sign
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:genshin-sign"
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/genshin-sign:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/genshin-sign:${{ env.VER }}
      -
        name: Build and push AutoMihoyoBBS
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:AutoMihoyoBBS"
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/AutoMihoyoBBS:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/AutoMihoyoBBS:${{ env.VER }}
